//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "schedule")]
pub struct Model {
    #[sea_orm(unique)]
    pub id: Uuid,
    pub title: String,
    pub day: Date,
    pub start_time: DateTimeWithTimeZone,
    pub end_time: DateTimeWithTimeZone,
    pub activity_type: String,
    pub location: String,
    pub priority: String,
    pub notes: String,
    pub status: String,
    pub alert_time: DateTimeWithTimeZone,
    pub duration: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
